<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;
use Inertia\Response;

class RegisteredUserController extends Controller
{
    /**
     * Display the registration view.
     */
    public function create(): Response
    {
        return Inertia::render('Auth/Register');
    }

    /**
     * Handle an incoming registration request.
     *
     * @throws ValidationException
     */
    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|lowercase|email|max:255|unique:'.User::class,
            'password' => ['required', 'confirmed', Rules\Password::defaults()],
            'phone' => 'required|string|max:20',
            'address' => 'required|string',
        ]);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'role' => 'customer',
        ]);

        $pppoePassword = \Illuminate\Support\Str::random(6);

        $customer = \App\Models\Customer::create([
            'user_id' => $user->id,
            'phone' => $request->phone,
            'address' => $request->address,
            'pppoe_password' => $pppoePassword,
            'status' => 'inactive',
            'billing_date' => 1,
        ]);

        // Now that the customer_code is generated by the model boot method, update the PPPoE username
        $customer->update([
            'pppoe_username' => strtolower($customer->customer_code)
        ]);

        event(new Registered($user));

        return back()->with('success', 'Silakan login menggunakan akun yang baru saja Anda buat.');
    }
}
